services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - default

  backend:
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_SERVER: db
    build:
      context: ./backend
    ports:
      - ${BACKEND_PORT}:5000
    networks:
      - default

  db:
    image: mongo:5.0-focal
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./scripts:/scripts
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
    networks:
      - default
      
networks:
  default:

volumes:
  mongo-data:
    