services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - default

  backend:
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      BACKEND_DOMAIN: ${BACKEND_DOMAIN}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_ENVIRONMENT: ${BACKEND_ENVIRONMENT}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - ${BACKEND_PORT}:5000
    networks:
      - default

  db:
    image: mongo:5.0-focal
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./scripts:/scripts
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
    networks:
      - default
      
networks:
  default:

volumes:
  mongo-data:
    