services:
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 5173:5173
    networks:
      - default

  backend:
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_PORT: ${APP_PORT}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_BACKEND_CORS_ORIGINS: ${APP_BACKEND_CORS_ORIGINS}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - ${APP_PORT}:5000
    networks:
      - default

  db:
    image: mongo:5.0-focal
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./scripts:/scripts
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
    networks:
      - default
      
networks:
  default:

volumes:
  mongo-data:
    