[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Shahar Band <shahar1531@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
beanie = "^1.26.0"
pydantic = "^2.7.3"
pyjwt = "^2.8.0"
pytest = "^8.2.2"
bcrypt = "^4.1.3"
uvicorn = "^0.30.1"
pydantic-settings = "^2.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
